// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function hasExtension(extensionToFind, substring) {
  return new RegExp("\\" + (String(extensionToFind) + "\$")).test(substring);
}

exports.hasExtension = hasExtension;
/* No side effect */
